# Generated by Django 4.0 on 2024-05-03 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=3)),
                ('nick_name', models.CharField(max_length=100)),
            ],
        ),
    ]
