# Generated by Django 4.0 on 2024-05-03 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_avatars_persons_players_weapons_delete_person_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Avatars',
            new_name='Avatar',
        ),
        migrations.RenameModel(
            old_name='Persons',
            new_name='Person',
        ),
        migrations.RenameModel(
            old_name='Players',
            new_name='Player',
        ),
        migrations.RenameModel(
            old_name='Weapons',
            new_name='Weapon',
        ),
    ]
