# Generated by Django 4.0 on 2024-05-03 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_nick_name_player_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='owner',
        ),
        migrations.AddField(
            model_name='player',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.avatar'),
        ),
    ]
