# Generated by Django 4.0 on 2024-05-03 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_avatar_owner_player_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='owner',
            new_name='avatar',
        ),
        migrations.AlterField(
            model_name='person',
            name='player',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.player'),
        ),
    ]
